# SPDX-License-Identifier: GPL-2.0
dtbo-y += \
        a54x_eur_open_w00_r00.dtbo \
        a54x_eur_open_w00_r01.dtbo \
        a54x_eur_open_w00_r02.dtbo \
        a54x_eur_open_w00_r03.dtbo \
        a54x_eur_open_w00_r05.dtbo \
        a54x_eur_open_w00_r10.dtbo

dtbo-y += \
        a54x_chn_open_w00_r00.dtbo \
        a54x_chn_open_w00_r02.dtbo \
        a54x_chn_open_w00_r03.dtbo \
        a54x_chn_open_w00_r05.dtbo

dtbo-y += \
        a54x_chn_hk_w00_r00.dtbo \
        a54x_chn_hk_w00_r02.dtbo \
        a54x_chn_hk_w00_r03.dtbo \
        a54x_chn_hk_w00_r05.dtbo

dtbo-y += \
        a54x_kor_singlex_w00_r00.dtbo \
        a54x_kor_singlex_w00_r02.dtbo \
        a54x_kor_singlex_w00_r03.dtbo \
        a54x_kor_singlex_w00_r05.dtbo

dtbo-y += \
        a54x_sea_open_w00_r00.dtbo \
        a54x_sea_open_w00_r02.dtbo \
        a54x_sea_open_w00_r03.dtbo \
        a54x_sea_open_w00_r05.dtbo

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.reverse.dts *.dtbo
